on: [push, pull_request]

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "18.15.0"
            - name: Install dependencies
              run: npm ci
              shell: bash
            - name: Run tests
              run: npm t
              shell: bash
